services:
  HomeGlow-Backend:
    container_name: HomeGlow-Backend
    build:
      context: https://github.com/jherforth/homeglow.git#main:server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./tasks.db:/app/tasks.db
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_USERNAME}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - IMMICH_URL=${IMMICH_URL}
      - IMMICH_API_KEY=${IMMICH_API_KEY}
  HomeGlow-Frontend:
    container_name: HomeGlow-Frontend
    build:
      context: https://github.com/your-username/homeglow.git#main:client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - HomeGlow-Backend
    environment:
      - REACT_APP_API_URL=http://HomeGlow-Backend:5000