services:
  homeglow-backend:
    container_name: homeglow-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /apps/homeglow/data:/app/data
      - /apps/homeglow/uploads:/app/uploads # Ensure /apps/homeglow/uploads exists
    environment:
      - NODE_ENV=production
      - PORT=5000
  homeglow-frontend:
    container_name: homeglow-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
        - VITE_REACT_APP_API_URL=${VITE_REACT_APP_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - homeglow-backend
    environment:
      - VITE_REACT_APP_API_URL=http://homeglow-backend:5000
#  tailscale:
#    container_name: homeglow-tailscale
#    image: tailscale/tailscale:latest
#    volumes:
#      - /apps/homeglow/tailscale-state:/var/lib/tailscale # Updated to correct path
#    cap_add:
#      - NET_ADMIN
#    network_mode: service:homeglow-frontend
#    environment:
#      - TS_AUTHKEY=${TS_AUTHKEY}
#      - TS_USERSPACE=true
#      - TS_SERVE_HTTP=:3000
    restart: unless-stopped
