services:
  homeglow-backend:
    container_name: homeglow-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./tasks.db:/app/tasks.db
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
  homeglow-frontend:
    container_name: homeglow-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - homeglow-backend
    environment:
      - REACT_APP_API_URL=http://homeglow-backend:5000