services:
  homeglow-backend:
    container_name: homeglow-backend
    build:
      context: /homeglow/server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /homeglow/data:/app/data
      - /homeglow/uploads:/app/uploads # Ensure /homeglow/uploads exists
    environment:
      - NODE_ENV=production
      - PORT=5000
  homeglow-frontend:
    container_name: homeglow-frontend
    build:
      context: /homeglow/client
      dockerfile: Dockerfile
      args:
        - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
        - VITE_REACT_APP_API_URL=${VITE_REACT_APP_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - homeglow-backend
    env_file:
      - /homeglow/.env # Ensure .env exists in /homeglow
    environment:
      - VITE_REACT_APP_API_URL=http://homeglow-backend:5000
  tailscale:
    container_name: homeglow-tailscale
    image: tailscale/tailscale:latest
    hostname: homeglow-tailscale
    volumes:
      - /homeglow/tailscale-state:/var/lib/tailscale # Ensure /homeglow/tailscale-state exists
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_ADVERTISE_ROUTES=172.17.0.0/16
    restart: unless-stopped